name: '.NET Library Build and Release'
description: 'A Composite Action that Builds, Publishes and Releases a .NET 7+ Library'
author: 'RICADO'
branding:
  icon: 'link'
  color: 'blue'

# Inputs
inputs:
  project-name:
    description: 'The Project Name (e.g. RICADO.Logging)'
    required: true
  github-token:
    description: 'The GitHub Token used to Generate a Changelog and Create Releases'
    required: true
  private-nuget-url:
    description: 'The URL of the Private NuGet Repository (e.g. https://nuget.pkg.github.com/myname/index.json)'
    required: true
  private-nuget-token:
    description: 'The Token used for Authentication with the Private NuGet Repository'
    required: true
  public-nuget-url:
    description: 'The URL of the Public NuGet Repository (e.g. https://api.nuget.org/v3/index.json)'
    required: false
    default: 'https://api.nuget.org/v3/index.json'
  public-nuget-user:
    description: 'The Username (Profile Name) of the NuGet.org Account used for Trusted Publishing with the Public NuGet Repository'
    required: false
  publish-public:
    description: 'Whether the Library should be Published to the Public NuGet Repository'
    required: false
    default: 'false'
  dotnet-version:
    description: 'The .NET SDK Version to be used for Builds (e.g. 7.0.x)'
    required: false
    default: '7.0.x'

# Outputs
outputs:
  changelog:
    description: 'Markdown formatted changelog'
    value: ${{ steps.changelog.outputs.changelog }}

runs:
  using: 'composite'
  steps:
    # Setup .NET with GitHub Packages Authentication
    - name: Setup .NET with GitHub Packages Authentication
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
        source-url: ${{ inputs.private-nuget-url }}
      env:
        NUGET_AUTH_TOKEN: ${{ inputs.private-nuget-token }}
    
    # Restore NuGet Packages
    - name: Restore NuGet Packages
      run: dotnet restore "${{ inputs.project-name }}/${{ inputs.project-name }}.csproj"
      shell: bash
    
    # Build the Library
    - name: Build the Library
      run: dotnet build "${{ inputs.project-name }}/${{ inputs.project-name }}.csproj" -c Release --no-restore
      shell: bash
    
    # Pack the Library
    - name: Pack the Library
      if: ${{ github.ref_type == 'tag' }}
      run: dotnet pack "${{ inputs.project-name}}/${{ inputs.project-name }}.csproj" -c Release -p:PackageVersion=${{ github.ref_name }}
      shell: bash
    
    # Generate the Changelog
    - name: Generate the Changelog
      id: changelog
      if: ${{ github.ref_type == 'tag' }}
      uses: metcalfc/changelog-generator@v4
      with:
        mytoken: ${{ inputs.github-token }}
    
    # Create Draft GitHub Release
    - name: Create Draft GitHub Release
      id: create-draft-release
      if: ${{ github.ref_type == 'tag' }}
      uses: ncipollo/release-action@v1
      with:
        body: ${{ steps.changelog.outputs.changelog }}
        draft: true
        name: Version ${{ github.ref_name }}
        tag: ${{ github.ref_name }}
        token: ${{ inputs.github-token }}
    
    # Push the Package to GitHub Packages
    - name: Push the Package to GitHub Packages
      if: ${{ github.ref_type == 'tag' }}
      run: dotnet nuget push "${{ inputs.project-name }}/bin/Release/*.nupkg" -k ${{ inputs.private-nuget-token }} -s "${{ inputs.private-nuget-url }}" --skip-duplicate
      shell: bash
    
    # Get NuGet API Key
    - name: Get NuGet API Key
      id: nuget-login
      if: ${{ github.ref_type == 'tag' && inputs.publish-public == 'true' }}
      uses: NuGet/login@v1
      with:
        user: ${{ inputs.public-nuget-user }}
    
    # Push the Package to NuGet
    - name: Push the Package to Nuget
      if: ${{ github.ref_type == 'tag' && inputs.publish-public == 'true' }}
      run: dotnet nuget push "${{ inputs.project-name }}/bin/Release/*.nupkg" -k ${{ steps.nuget-login.outputs.NUGET_API_KEY }} -s "${{ inputs.public-nuget-url }}" --skip-duplicate
      shell: bash
    
    # Publish GitHub Release
    - name: Publish GitHub Release
      id: publish-release
      if: ${{ github.ref_type == 'tag' }}
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        draft: false
        omitBodyDuringUpdate: true
        omitNameDuringUpdate: true
        tag: ${{ github.ref_name }}
        token: ${{ inputs.github-token }}
        updateOnlyUnreleased: true
        body: ${{ steps.changelog.outputs.changelog }}
        name: Version ${{ github.ref_name }}
